python -u executor.py \
  --model_des SkAB_train \
  --exp_des SkAB_train \
  --dataset SkAB \
  --region Russia \
  --model adj_ns_DLinear \
  --forcast_task M \
  --neighbor_window 20 \
  --n_index 8 \
  --sample_time_window_before 180 \
  --sample_time_window_after 0 \
  --sample_day_window 0 \
  --train_epochs 10 \
  --train_ratio 0.7 \
  --test_ratio 0.1 \
  --anomaly_class_weight 1.08 \
  --seq_len 180 \
  --label_len 48 \
  --pred_len 1 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --gpu 0 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --itr 1 