python -u executor.py \
  --model_des SMD_train \
  --exp_des SMD_train \
  --dataset SMD \
  --model ns_Autoformer \
  --forcast_task M \
  --n_index 38 \
  --sample_time_window_before 30 \
  --sample_time_window_after 0 \
  --sample_day_window 14 \
  --train_ratio 0.7 \
  --test_ratio 0.1 \
  --seq_len 464 \
  --label_len 48 \
  --pred_len 1 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --gpu 0 \
  --enc_in 38 \
  --dec_in 38 \
  --c_out 38 \
  --itr 1